// Currencies action types
// Fetch actions
export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
export const REQUEST_CURRENCIES_SUCCESS = 'REQUEST_CURRENCIES_SUCCESS';
export const REQUEST_CURRENCIES_FAIL = 'REQUEST_CURRENCIES_FAIL';

// Select actions
export const SELECT_CURRENCY = 'SELECT_CURRENCY';
export const REMOVE_SELECTED_CURRENCY = 'REMOVE_SELECTED_CURRENCY';
